cpverify -addreg -file «C:\Windows\SysWOW64\inetcomm.dll»
cpverify -addreg -file «C:\Windows\SysWOW64\schannel.dll»
cpverify -addreg -file «C:\Windows\SysWOW64\wininet.dll»
cpverify -addreg -file «C:\Windows\SysWOW64\certenroll.dll»
cpverify -addreg -file «C:\Windows\system32\certenroll.dll»
cpverify -addreg -file «C:\Windows\system32\schannel.dll»
cpverify -addreg -file «C:\Windows\system32\wininet.dll»
cpverify -addreg -file «C:\Windows\system32\msi.dll»
cpverify -addreg -file «C:\Windows\system32\inetcomm.dll»
cpverify -addreg -file «C:\Windows\system32\sspicli.dll»
cpverify -addreg -file «C:\Windows\system32\crypt32.dll»
cpverify -addreg -file «C:\Windows\system32\kerberos.dll»